import { ResourceType } from '../components/knowledgebase/types/KnowledgeBase';
import { ZSIQTabs } from '../types/Listener';
import RNZohoSalesIQ from './utils';

export const ZSIQListenerEvents = {
  EVENT_SUPPORT_OPENED: RNZohoSalesIQ.SUPPORT_OPENED,
  EVENT_SUPPORT_CLOSED: RNZohoSalesIQ.SUPPORT_CLOSED,
  EVENT_VISITOR_IPBLOCKED: RNZohoSalesIQ.VISITOR_IPBLOCKED,
  EVENT_OPERATORS_ONLINE: RNZohoSalesIQ.OPERATORS_ONLINE,
  EVENT_OPERATORS_OFFLINE: RNZohoSalesIQ.OPERATORS_OFFLINE,

  EVENT_CHATVIEW_OPENED: RNZohoSalesIQ.CHATVIEW_OPENED,
  EVENT_CHATVIEW_CLOSED: RNZohoSalesIQ.CHATVIEW_CLOSED,
  EVENT_CHAT_OPENED: RNZohoSalesIQ.CHAT_OPENED,
  EVENT_CHAT_CLOSED: RNZohoSalesIQ.CHAT_CLOSED,
  EVENT_CHAT_REOPENED: RNZohoSalesIQ.CHAT_REOPENED,
  EVENT_CHAT_ATTENDED: RNZohoSalesIQ.CHAT_ATTENDED,
  EVENT_CHAT_MISSED: RNZohoSalesIQ.CHAT_MISSED,
  EVENT_CHAT_QUEUE_POSITION_CHANGED: RNZohoSalesIQ.CHAT_QUEUE_POSITION_CHANGED,
  EVENT_CHAT_UNREAD_COUNT_CHANGED: RNZohoSalesIQ.CHAT_UNREAD_COUNT_CHANGED,
  EVENT_FEEDBACK_RECEIVED: RNZohoSalesIQ.FEEDBACK_RECEIVED,
  EVENT_RATING_RECEIVED: RNZohoSalesIQ.RATING_RECEIVED,

  EVENT_ARTICLE_LIKED: RNZohoSalesIQ.ARTICLE_LIKED,
  EVENT_ARTICLE_DISLIKED: RNZohoSalesIQ.ARTICLE_DISLIKED,
  EVENT_ARTICLE_OPENED: RNZohoSalesIQ.ARTICLE_OPENED,
  EVENT_ARTICLE_CLOSED: RNZohoSalesIQ.ARTICLE_CLOSED,
  EVENT_PERFORM_CHATACTION: RNZohoSalesIQ.PERFORM_CHATACTION,
  EVENT_CUSTOMTRIGGER: RNZohoSalesIQ.CUSTOMTRIGGER,
  EVENT_BOT_TRIGGER: RNZohoSalesIQ.BOT_TRIGGER,
  EVENT_HANDLE_URL: RNZohoSalesIQ.EVENT_HANDLE_URL,

  EVENT_RESOURCE_OPENED: RNZohoSalesIQ.EVENT_RESOURCE_OPENED,
  EVENT_RESOURCE_CLOSED: RNZohoSalesIQ.EVENT_RESOURCE_CLOSED,
  EVENT_RESOURCE_LIKED: RNZohoSalesIQ.EVENT_RESOURCE_LIKED,
  EVENT_RESOURCE_DISLIKED: RNZohoSalesIQ.EVENT_RESOURCE_DISLIKED,

  EVENT_HANDLE_CUSTOM_LAUNCHER_VISIBILITY:
    RNZohoSalesIQ.EVENT_HANDLE_CUSTOM_LAUNCHER_VISIBILITY,

  EVENT_NOTIFICATION_CLICKED: RNZohoSalesIQ.EVENT_NOTIFICATION_CLICKED,
};

export const ZSIQConstants = {
  ...ZSIQListenerEvents,

  Tab: ZSIQTabs,
  TYPE_OPEN: RNZohoSalesIQ.TYPE_OPEN,
  TYPE_WAITING: RNZohoSalesIQ.TYPE_WAITING,
  TYPE_CONNECTED: RNZohoSalesIQ.TYPE_CONNECTED,
  TYPE_ENDED: RNZohoSalesIQ.TYPE_ENDED,
  TYPE_CLOSED: RNZohoSalesIQ.TYPE_CLOSED,
  TYPE_MISSED: RNZohoSalesIQ.TYPE_MISSED,
  // DEPRECATED
  LAUNCHER_MODE_STATIC: RNZohoSalesIQ.LAUNCHER_MODE_STATIC,
  // DEPRECATED
  LAUNCHER_MODE_FLOATING: RNZohoSalesIQ.LAUNCHER_MODE_FLOATING,
  ActionSource: {
    APP: RNZohoSalesIQ.ACTION_SOURCE_APP,
    SDK: RNZohoSalesIQ.ACTION_SOURCE_SDK,
  },
  Resource: ResourceType,
};
